import { Submission } from '@/types/database';

export const INITIAL_APPROVED_SUBMISSIONS: Submission[] = [
  {
    id: '1a9e3458-7652-47b8-8090-f92e48231201',
    student_name: 'سارة خالد العتيبي',
    title: 'إعادة تدوير العبوات البلاستيكية لإنتاج ألياف صديقة للبيئة',
    description: 'مشروع كيميائي مدرسي يوضح كيفية تحويل بوليمر البولي إيثيلين تيرفثالات (PET) المستهلك إلى ألياف نسيجية ومجسمات نباتية تخدم الحدائق المدرسية وتقليل النفايات.',
    category: 'إعادة تدوير',
    file_url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
    file_path: null,
    status: 'approved',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    reviewed_at: new Date(Date.now() - 86400000).toISOString(),
    reviewed_by: null,
    admin_note: 'مبادرة متميزة ومكتملة الأركان العلمية.',
  },
  {
    id: '2b8f4569-8763-48c9-91a1-a03f59342312',
    student_name: 'ريم فهد الشمري',
    title: 'ابتكار نظام ذكي لترشيد الري المدرسي باستخدام حساسات رطوبة التربة',
    description: 'تم تصميم دارة إلكترونية مرتبطة بحساسات رطوبة تقيس المحتوى المائي في حوض نباتات المدرسة لتقليل هدر المياه بنسبة 45% وتحقيق استدامة مائية فعالة.',
    category: 'ترشيد المياه',
    file_url: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=800&q=80',
    file_path: null,
    status: 'approved',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    reviewed_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    reviewed_by: null,
    admin_note: 'تطبيق عملي رائع لربط الكيمياء بالتقنية الحديثة.',
  },
  {
    id: '3c7e5670-9874-49da-a2b2-b14a60453423',
    student_name: 'نوف عبدالعزيز الحربي',
    title: 'استخلاص أصباغ طبيعية آمنة من بقايا قشور الرمان والشمندر',
    description: 'دراسة كيميائية لاستخراج صبغات الأنثوسيانين العضوية واستخدامها في التلوين المدرسي كبديل للأصباغ الصناعية الكيميائية غير القابلة للتحلل.',
    category: 'مشروع كيمياء خضراء',
    file_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80',
    file_path: null,
    status: 'approved',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    reviewed_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    reviewed_by: null,
    admin_note: 'فكرة إبداعية في مجال الكيمياء الخضراء.',
  },
  {
    id: '4d6f6781-0985-4aeb-b3c3-c25b71564534',
    student_name: 'مها سلطان الدوسري',
    title: 'مبادرة غرس النباتات الصحراطية المحلية وتثبيت الكربون',
    description: 'زراعة 30 شتلة من شجر الغاف والرمث في ساحة الحي مع توثيق كيميائي لقدرتها الفائقة على امتصاص غاز الكربون وتحمل الجفاف وملوحة التربة.',
    category: 'تشجير',
    file_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    file_path: null,
    status: 'approved',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    reviewed_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    reviewed_by: null,
    admin_note: 'جهد وطني مبارك يدعم مبادرة السعودية الخضراء.',
  },
];
